#! /usr/bin/perl

use strict;

# use Barefoot::debug;							# comment out for production

use Getopt::Std;
use Cwd qw(getcwd);
use Barefoot::cvs;
use Barefoot::input qw(get_yn);

my $me = $0;
$me =~ s@^.*/@@;

# default values
my $verbose=0;
my $cvsroot=$::ENV{CVSROOT};


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

my $opt = {};
getopts('vd:', $opt);
$verbose = 1 if defined $opt->{v};
$cvsroot = $opt->{d} if defined $opt->{d};


#################################
# CHECK FOR ERRORS
#################################

if (!$cvsroot)
{
	print STDERR "$me: variable CVSROOT must be set\n";
	exit 2;
}

my $offsite = cvs::is_offsite($cvsroot);

my $module = $ARGV[0];

if (!$module)
{
	print STDERR "usage: $me module\n";
	exit 2;
}

if (!-r $module)
{
	print STDERR "$me: $module does not exist or is not readable\n";
	exit 2;
}

my ($project, $subdir) = cvs::parse_module(getcwd());
if ( !$offsite )
{
	if (!-e "$cvsroot/$project/$subdir/$module,v")
	{
		print "$cvsroot/$project/$subdir/$module,v\n";
		print STDERR "$me: $module does not appear to be checked into CVS\n";
		exit 2;
	}
}


#################################
# MAIN
#################################

my @lockers = cvs::getLockers($cvsroot, $module);
my $username = $::ENV{USER};
$username = $::ENV{USERNAME} if !$username;
if (!grep {$_ eq $username} @lockers)
{
	print "$me: you didn't do a get on this module\n";
	exit 1;
}


system("cvs -d $cvsroot unedit $module");
system("cvs -d $cvsroot watch remove -a edit $module");
if ( !$offsite )
{
	my $prgrp = cvs::project_group($project);
	system("chgrp $prgrp $module") unless $?;
	system("chmod a+r $module") unless $?;
}

print "done\n" unless $?;
