#! /usr/bin/perl

use strict;
use warnings;

use Cwd qw(getcwd);

use VCtools::Base;
use VCtools::Common;


#################################
# OPTIONS AND ARGUMENTS
#################################

VCtools::process_args("project");

my $project = $ARGV[0];


#################################
# CHECK FOR ERRORS
#################################

VCtools::fatal_error("must be run from top-level personal testing directory")
		if getcwd() ne VCtools::WORKING_DIR;
VCtools::fatal_error("project $project does not exist in VC")
		unless VCtools::proj_exists_in_vc($project);
VCtools::fatal_error("project $project already exists") if -e $project;

# check for proper group
VCtools::verify_gid($project);


#################################
# MAIN
#################################

# leaving second argument blank indicates we want the entire project
VCtools::get_tree($project, "", $project);

# check for post-build script and execute it
foreach (VCtools::project_script($project, 'PostBuild'))
{
	print "$_\n" if VCtools::verbose;
	system($_) == 0
			or VCtools::fatal_error("script line failed; check config file");
}

print "done\n" unless $?;


#################################
# SUBS
#################################
