#! /usr/bin/perl

use strict;

use Geek::Dev::Debug(1);

use Cwd qw(getcwd);

use VCtools::common;


#################################
# OPTIONS AND ARGUMENTS
#################################

VCtools::process_args("project");

my $project = $ARGV[0];

#################################
# CHECK FOR ERRORS
#################################

VCtools::fatal_error("must be run from top-level personal testing directory")
		if getcwd() ne VCtools::WORKING_DIR;
VCtools::fatal_error("project $project does not exist in VC")
		unless VCtools::proj_exists_in_vc($project);
VCtools::fatal_error("project $project already exists") if -e $project;

# check for proper group
VCtools::verify_gid($project);


#################################
# MAIN
#################################

# leaving second argument blank indicates we want the entire project
VCtools::get_tree($project, "", $project);
print "done\n" unless $?;


#################################
# SUBS
#################################
