#! /usr/bin/perl

###########################################################################
#
# vdel
#
###########################################################################
#
# This command removes files from VC (technically, it removes them from the HEAD of either trunk or branch,
# whichever the working copy is pointing at).  It also commits the removal.
#
# #########################################################################
#
# All the code herein is released under the Artistic License
#		( http://www.perl.com/language/misc/Artistic.html )
# Copyright (c) 2001-2008 Barefoot Software, Copyright (c) 2004-2007 ThinkGeek
#
###########################################################################

use strict;
use warnings;

use DirHandle;
use Cwd qw<getcwd>;

use VCtools::Base;
use VCtools::Args;
use VCtools::Common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::switch('recursive', 'r', 'operate recursively');
VCtools::switch('force', 'f', "don't ask any questions");
VCtools::args('files', 'list', 'file(s) (or directory/ies) to remove from VC');
VCtools::getopts();

# remember, directories are files too
my @files = VCtools::files();


#################################
# CHECK FOR ERRORS
#################################

VCtools::verify_files_and_group(@files);
my $opts = { DONT_RECURSE => !VCtools::recursive() };

# get statuses for everything at once (quicker that way)
VCtools::cache_file_status(@files, { DONT_RECURSE => !VCtools::recursive() });

foreach my $file (@files)
{
	VCtools::fatal_error("$file is not in VC") unless VCtools::exists_in_vc($file);
}


#################################
# MAIN
#################################

unless (VCtools::force())
{
	VCtools::prompt_to_continue("$_ is going to be removed from VC and then deleted") foreach @files;
}

VCtools::remove_files(@files, $opts);
VCtools::commit_files(undef, @files,									# HACK! when first arg removed from lib, remove here
		{ %$opts, DEL => scalar(@files) });

print "done\n";
