#! /usr/bin/perl

use strict;
use warnings;

use DirHandle;
use Cwd qw<getcwd>;

use VCtools::Base;
use VCtools::Args;
use VCtools::Common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

#VCtools::switch('recursive', 'r', 'operate recursively');
VCtools::switch('force', 'f', "don't ask any questions");
VCtools::args('files', 'list', 'file(s) (or directory/ies) to remove from VC');
VCtools::getopts();

# remember, directories are files too
my @files = VCtools::files();


#################################
# CHECK FOR ERRORS
#################################

my $proj = VCtools::verify_files_and_group(@files);

# get statuses for everything at once (quicker that way)
VCtools::cache_file_status(@files, { DONT_RECURSE => 1 });

foreach my $file (@files)
{
	VCtools::fatal_error("$file is not in VC") unless VCtools::exists_in_vc($file);
}


#################################
# MAIN
#################################

unless (VCtools::force())
{
	VCtools::prompt_to_continue("$_ is going to be removed from VC and then deleted") foreach @files;
}

VCtools::remove_files(@files);
VCtools::commit_files($proj, @files, { DEL => scalar(@files) });

print "done\n";
