#! /usr/bin/perl

use strict;
use warnings;

use VCtools::Base;
use VCtools::Args;
use VCtools::Common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::args('file', 'single', 'file to show diffs of');
VCtools::getopts();

# remember, directories are files too
my $file = VCtools::file();


#################################
# CHECK FOR ERRORS
#################################

VCtools::check_common_errors();
VCtools::verify_files_and_group($file);

#################################
# MAIN
#################################

# create a temporary filename
my $tmpdir = $ENV{TMP} || $ENV{TEMP} || "/tmp";
my $tmpfile = "$tmpdir/vcdiff" . "_$$.out";

# execute diff and put into the tmpfile
open(TMP, ">$tmpfile") or fatal_error("cannot create temp file $tmpfile");
print TMP VCtools::get_diffs($file);
close(TMP);

# view the diff
my $pager = $ENV{PAGER} || "less";
system("$pager $tmpfile");

# remove the temp file
unlink($tmpfile);
