#! /usr/bin/perl

use strict;
use warnings;

use VCtools::Base;
use VCtools::Args;
use VCtools::Common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::switch('blanks', 'b', 'ignore differences in amounts of whitespace');
VCtools::args('file', 'single', 'file to show diffs of');
VCtools::getopts();

# remember, directories are files too
my $file = VCtools::file();


#################################
# CHECK FOR ERRORS
#################################

VCtools::verify_files_and_group($file);

#################################
# MAIN
#################################

# execute diff and page it out to STDOUT
VCtools::page_output('.vcdiff', VCtools::get_diffs($file, { IGNORE_BLANKS => VCtools::blanks() }));
