#! /usr/bin/perl

use strict;
use warnings;

use Geek::Dev::Debug(1);

use Getopt::Std;
use Cwd qw(getcwd);

use VCtools::common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::process_args("file_or_dir [...]");

# remember, directories are files too
my @files = @ARGV;


#################################
# CHECK FOR ERRORS
#################################

foreach my $file (@files)
{
	VCtools::fatal_error("$file does not exist")
			unless -e $file;
	VCtools::fatal_error("$file is not in VC working dir")
			unless VCtools::parse_module($file);
}

# get statuses for everything at once (quicker that way)
VCtools::cache_file_status(@files);

foreach my $file (@files)
{
	VCtools::fatal_error("$file is already in VC")
			if VCtools::exists_in_vc($file);
}


#################################
# MAIN
#################################

if ( $^O =~ /MSWin32/ )
{
	open(ADD, "cvs -d $cvsroot add $module |") or 
								die "can't execute cvs add\n"; 
}
else
{
	open(ADD, "cvs -d $cvsroot add $module 2>&1 |") or 
								die "can't execute cvs add\n"; 
}

while ( <ADD> )
{
	chomp;
	next if ( /use \'cvs commit\'/ || /^done/ );
	
	if ( /server\: (.*)/ )
	{
		print "$me: $1\n";
	}
	else
	{
		# don't know what this line is
		print "$me: $_\n";
	}
}
close(ADD);


# commit is not needed for directories
unless (-d $module)
{
	if ( $^O =~ /MSWin32/ )
	{
		open(COM, "cvs -r -d $cvsroot commit -m\"initial version\" $module |") 
			unless $?;
	}
	else
	{
		open(COM, "cvs -r -d $cvsroot commit -m\"initial version\" $module 2>&1 |") 
			unless $?;
	}

	while ( <COM> )
	{
		chomp;
		next if ( /^done/ );
			
		if ( /server\: (.*)/ )
		{
			print "$me: $1\n";
		}
		else
		{
			# don't know what this line is
			print "$me: $_\n";
		}
	}
	close(COM);

	# don't think this is needed with -r above, regardless won't work offsite
	if ( !$offsite )
	{
		system("chmod a-w $module") unless $?;
	}
}

print "done\n" unless $?;
