#! /usr/bin/perl

use strict;
use warnings;

use Geek::Dev::Debug(1);

use File::Find;

use VCtools::common;


my $pattern = $ARGV[0];

my %possible_dirs;
find sub
	{
		if ($_ eq "CVS")
		{
			$File::Find::prune = 1;
		}
		else
		{
			is_possible($_, $File::Find::name)
					if /^$pattern/o and -d $File::Find::name;
		}
	}, VCtools::WORKING_DIR;
my @dirs = sort {
		$possible_dirs{$a} <=> $possible_dirs{$b} || $a cmp $b
	} keys %possible_dirs;
print "$dirs[0]\n";


sub is_possible
{
	my ($subdir, $fulldir) = @_;

	# count the number of subdirs
	# this allows us to rank choices by how "deep" they are
	my $depth = ($fulldir =~ s@/@/@g) || 0;

	# we want exact matches to rank higher than partials
	# thus we add a large number to non-exact matches, making them drop
	# low in the sorting
	$possible_dirs{$fulldir} = $depth + ($subdir eq $pattern ? 0 : 100);
}
