#! /usr/bin/perl

use strict;
use warnings;

use VCtools::Base;
use VCtools::Args;
use VCtools::Common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::switch('recursive', 'r', 'operate recursively');
VCtools::switch('show_branches', 'b', 'show the branch name (or TRUNK if no branch) for all files');
VCtools::args('files', 'optlist', 'file(s) (or directory/ies) to show status of (default .)');
VCtools::getopts();

# remember, directories are files too
my @files = VCtools::files();
@files = (".") unless @files;
print STDERR "status for files: @files\n" if DEBUG >= 3;


#################################
# CHECK FOR ERRORS
#################################

my $proj = VCtools::verify_files_and_group(@files);


#################################
# MAIN
#################################

my $retval = VCtools::print_status($proj, @files, { SHOW_BRANCHES => VCtools::show_branches() });

exit $retval;							# should be 1 if any errors


#################################
# SUBS
#################################
