#! /usr/bin/perl

use strict;
use warnings;

use Geek::Dev::Debug(1);

use Getopt::Std;

use VCtools::common;


#################################
# OPTIONS AND ENVIRONMENT VARS
#################################

VCtools::process_args( {
		r   =>  {
			name    =>  'recursive',
			usage   =>  '[-r]',
			comment =>  'apply operation recursively',
		},
	}, "[file_or_dir ...]");

# remember, directories are files too
my @files = @ARGV || ".";


#################################
# CHECK FOR ERRORS
#################################

VCtools::verify_files_and_group(@files);

# get statuses for everything at once (quicker that way)
VCtools::cache_file_status(@files);

foreach my $file (@files)
{
	VCtools::fatal_error("$file is not in VC")
			unless VCtools::exists_in_vc($file);
}


#################################
# MAIN
#################################

VCtools::update_files(@files);

print "done\n" unless $?;


#################################
# SUBS
#################################
